### ISSUE TITLE
Can not load database due to dlopen error

### ISSUE THREAD

**Issue by tmatrai** [moovida/flutter_geopackage#3]
First of all, thanks for this great project!

On IOS it works like a charm, but on Android (both on emulator and and physical device) I have problem when opening a database, even if storage permission is granted.

ArgumentError (Invalid argument(s): Failed to load dynamic library (dlopen failed: library "/data/data/com.xy.geoplayground/lib/libsqlite3.so" not found))

Here is the stack:
```
I/flutter (25839): copying gpkg files...
I/flutter (25839): copying done
I/flutter (25839): Error while copying:
I/flutter (25839): Invalid argument(s): Failed to load dynamic library (dlopen failed: library "/data/data/com.xy.geoplayground/lib/libsqlite3.so" not found)
[38;5;244mI/flutter (25839): #0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:55)[39;49m
[38;5;244mI/flutter (25839): #1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:20:12)[39;49m
[38;5;248mI/flutter (25839): #2      _defaultOpen[39;49m
 package:sqlite3/src/load_library.dart
[38;5;248mI/flutter (25839): #3      OpenDynamicLibrary.openSqlite[39;49m
 package:sqlite3/src/load_library.dart
[38;5;248mI/flutter (25839): #4      sqlite3[39;49m
 package:sqlite3/…/api/sqlite3.dart
[38;5;248mI/flutter (25839): #5      sqlite3 (package:sqlite3/src/api/sqlite3.dart)[39;49m
 package:sqlite3/…/api/sqlite3.dart
[38;5;248mI/flutter (25839): #6      SqliteDb.open[39;49m
 package:dart_hydrologis_db/…/dart_db/sqlite.dart
[38;5;248mI/flutter (25839): #7      GeopackageDb.openOrCreate[39;49m
 package:flutter_geopackage/…/flutter_geopackage/geopackage.dart
[38;5;248mI/flutter (25839): #8      ConnectionsHandler.open[39;49m
 package:flutter_geopackage/…/flutter_geopackage/geopackage.dart
[38;5;248mI/flutter (25839): #9      _GeoPackagePageState._loadData[39;49m
 package:nvcplayground/ui/geopackagepage.dart
[38;5;248mI/flutter (25839): #10     _GeoPackagePageState._loadGeoPackage.<anonymous closure>[39;49m
 package:geoplayground/ui/geopackagepage.dart
I/flutter (25839): <asynchronous suspension>
I/flutter (25839): #11     _GeoPackagePageState._loa

```
What do I miss? I used code from your sample project.

Thanks a lot!

**Comment by moovida** [comment]
Did you create dependency on the sqlite3_flutter_libs package? It is necessary on Android by the underlying sqlite3 plugin to ship the native library.

**Comment by tmatrai** [comment]
Thanks a lot, a missed that step. I have added it just now, and it is okkey! :)

I checked your example project's dependencies before, and I could not find this reference in pubspec.yaml.

**Comment by moovida** [comment]
I think I missed the step. I probably tested it on macos where the step is not required... would be good to add it though. Else people could not know. :-)
